### ISSUE TITLE
Going FullScreen breaks the Viewport

### ISSUE THREAD

**Issue by kroaton** [zouiqad/UE5_Plugin-EditorUIScale#1]
Hey, I noticed that when using this at 4K, setting my UIScale to 0.8 and pressing F11 it will break the main Viewport. It doesn't fully scale, and I can see the sidebars covering half of the screen.
I'll try to investigate when I have some free time, but probably adding a hook to turn UIScale off when going full-screen would solve this.

**Comment by zouiqad** [comment]
Hey, so i took a look at it and indeed it breaks the main viewport regardless of the screen resolution, i added a check when going immersive (fullscreen) mode the application scale is set back to 1.f (transition might not be as smooth cause we're resizing the editor), i added a tick function to the module that checks every tick if viewport is in fullscreen, not optimal but from the research i did the engine doesn't fire an event when going immersive mode.

You can now pull (or download the latest build & delete previous version and replace it with new one in your project).

I didnt really test it much but it seems working, feel free to test it out and let me know if you encounter any further issues.

**Comment by kroaton** [comment]
Awesome, glad to know it wasn't just on my setup. Will test and let you know if I find anything wrong or if I can uncover a better hook to avoid ticking all the time.
